/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleCoin } from "./SimpleCoin";
export type { SimpleCrowdsale } from "./SimpleCrowdsale";

export { SimpleCoin__factory } from "./factories/SimpleCoin__factory";
export { SimpleCrowdsale__factory } from "./factories/SimpleCrowdsale__factory";
