/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleCoin } from "./SimpleCoin";

export { SimpleCoin__factory } from "./factories/SimpleCoin__factory";
